# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9c0451b0e800e3c0452663c616abf2cef6d09ece77c7fa9f60034a931b4e588ab23efe27ab2a52f976989e9e3490561b34021155b6542019c5cb321ad30a9f6c

test:
  secret_key_base: 0567f471888ad4552876731e77f10311cca155a44b82e3af363026e393f38b81c8b30b6e87ffcdffa1b32fbbdb3c79c934be033c8d8a2449cd3c56a877e31dd0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
